Modified main.py
protocollabs/aiohttp-login-session pull request #4
Opened 2018-03-23 13:23 UTC by muthuubalakan

main.py modified with good understandable comments. 
Implemented cookie_check function for checking the valid cookie on every page user visiting.

2018-03-23 19:06 UTC, hgn requested changes

2018-03-23 19:06 UTC, hgn commented on main.py
> +Required Python-3 or 3+
no, please add a shebang line, you also probably want to check a certain python version. asyncio was introduced in python x.y (google this). now you can add an check somewhere and if the required version is not sufficiently you can print a nice and helpful message and quit the execution.

2018-03-23 19:06 UTC, hgn commented on main.py
> +COOKIE_LIFE_TIME = 24*60*60*30
always spaces between operators:

```
COOKIE_LIFE_TIME = 24 * 60 * 60 * 30
```

2018-03-23 19:06 UTC, hgn commented on main.py
> +User ='Hippod'
no, it is global define, all global defines should be uppercase, like the other. Anyway, please ask yourself, is it cool when the style look not identical some lines down? Your answer should be: "no, it looks somehow shitty, i adjust the style". So User -> USER, probably use USERNAME, not just user. This is more exact. Always be so exact as possible if you name variables

2018-03-23 19:06 UTC, hgn commented on main.py
> +def cookie_check(request):
wait! Where do you comment a function and where do other comment functions? Do not invent your own style.

It is time that you should read this (referenced by pep8): https://www.python.org/dev/peps/pep-0257/

2018-03-23 19:06 UTC, hgn commented on main.py
> +    Check = cookie_check(request)
no, please read pep8, Check is not how you should name local variables

2018-03-23 19:06 UTC, hgn commented on main.py
>          page = open('site.html').read()
if think it is time to replace this construct: `open('site.html').read()`

What is the problem? Well, you do no error handling at all! What if the file is not available? The program crash! This should never happens!

Please extend and use (somehow, never tried it):

```
def prepare_file(filepath):
    if not os.isfile(filepath):
         print("internal server error, file not found: {}".format(filepath))
         return "<html>INTERNAL SERVER ERROR<html>"
    return open('site.html').read()
```

2018-03-23 19:06 UTC, hgn commented on main.py
> +        if username == User:
here, the problems comes into play, here `User` looks like a local variable! If you wrote it with UPPERCASE everybody knows instantly that you compare `username` with a global definition. Much more easy to follow the code.

2018-03-23 19:06 UTC, hgn commented on main.py
> +            if password == Password:
Please, I said that you should simplify the code, please check my old suggestion

2018-03-23 19:07 UTC, hgn commented
Beside the comments, the code looks far better then some days back! We are making progress! Some days and the code will look professional! :-) Thank you @muthuubalakan - good progress.

@lwrl please also check it again.

2018-03-29 14:22 UTC, muthuubalakan commented on main.py
> +        return True
Here the function can check for cookie with name and value! but somehow, in future, the name and value can be changed.

2018-03-29 14:51 UTC, hgn commented on main.py
> +    if COOKIE_VALUE == 0:
````
if cookie == COOKIE_VALUE:
      return True
return False
```

2018-03-29 14:51 UTC, merged